services:

  server:
    build: ./
    container_name: server
    ports:
      - 8000:8000
    depends_on:
      - whisper
      - redis
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
      - ./public:/app/public

  whisper:
    image: hwdsl2/whisper-server
    container_name: whisper
    restart: always
    expose:
      - 9000
    volumes:
      - whisper-data:/var/lib/whisper
    environment:
      - WHISPER_MODEL=large-v3
      - WHISPER_PORT=9000
      - WHISPER_DEVICE=auto
      - WHISPER_API_KEY=""

  redis:
    image: redis:8
    container_name: redis
    expose:
      - 6379

volumes:
  whisper-data:
    name: whisper-data